[theme]
primaryColor = "#E694FF"
backgroundColor = "#00172B"
secondaryBackgroundColor = "#0083B8"
textColor = "#FFFFFF"
font = "sans serif"

[server]
enableStaticServing = true
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false
maxMessageSize = 200

[runner]
fastReruns = true

[browser]
gatherUsageStats = false

[global]
developmentMode = false 
