[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FFFFFF"
font = "sans serif"

[server]
enableStaticServing = true
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false
maxMessageSize = 200

[runner]
fastReruns = true

[browser]
gatherUsageStats = false

[global]
developmentMode = false 
